@port=3000
@host=http://localhost:{{port}}

### GET /
GET {{host}}

### Get all employees
GET {{host}}/api/employees

### Get specific employee
GET {{host}}/api/employees/2

### Get nonexistent employee
GET {{host}}/api/employees/123

### Get random employee
GET {{host}}/api/employees/random

### Post new employee
POST {{host}}/api/employees
Content-Type: application/json

{
    "name": "New Guy"
}